title: Little Shaver's Machine
description: Instructions and documents for 4085

# theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: "false"